### ISSUE TITLE
Entity query

### ISSUE THREAD

**Issue by JohnnyXiangyu** [cuoshen/Geothermal#8]
Querying entities is the real core of what a user sees of ECS.
For simplicity, I think we can build it into systems. This might cause some flexibility issues, which I'll handle when they show up.
- [x] add interface in RuntimeSystem to represent their filter
- [ ] add code in Entity manager to actual filter out entities
- [ ] static routine at runtime that analyzes all runtime systems

**Comment by cuoshen** [comment]
Deprecated
